version: '3.4'

services:
  #basket.api:
  #  container_name: basket.api
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "CacheSettings:ConnectionString=basketdb:6379"
  #  depends_on:
  #    - basketdb
  #  ports:
  #    - "8001:80"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  #ocelotapigw:
  #  container_name: ocelotapigw
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  depends_on:
  #      - catalog.api
  #      - basket.api
  #  ports:
  #    - "8010:80"

  #shopping.aggregator:
  #  container_name: shopping.aggregator
  #  environment:
  #      - ASPNETCORE_ENVIRONMENT=Development
  #      - "ApiSettings:CatalogUrl=http://catalog.api"
  #      - "ApiSettings:BasketUrl=http://basket.api"
  #  depends_on:
  #      - catalog.api
  #      - basket.api
  #  ports:
  #      - "8005:80"

  #catalogdb:
  #  container_name: catalogdb
  #  restart: always
  #  ports:
  #      - "27017:27017"
  #  volumes:
  #      - mongo_data:/data/db

  #basketdb:
  #  container_name: basketdb
  #  restart: always    
  #  ports:
  #     - "6379:6379"